### ISSUE TITLE
How to use snake for json and form ?

### ISSUE THREAD

**Issue by ibadi-id** [maxnatchanon/vscode-go-struct-tag-autogen#5]
config:

```
"goStructTagAutogen.generation": {
        "tags": "json:\"{{snake}}\" groups:\"list,detail\" form:\"{{snake}}\""
    }
```

generate :

```
type Example struct {
	Name           string `json:"name" groups:"list,detail" form:"{{snake}}"`
	PersonalNumber string `json:"personal_number" groups:"list,detail" form:"{{snake}}"`
}
```

it should :

```
type Example struct {
	Name           string `json:"name" groups:"list,detail" form:"name"`
	PersonalNumber string `json:"personal_number" groups:"list,detail" form:"personal_number"`
}
```

and can we change or add custom tags like gorm or xorm ?

**Comment by maxnatchanon** [comment]
I've released [1.0.3](https://github.com/maxnatchanon/vscode-go-struct-tag-autogen/releases/tag/1.0.3) that should fix this bug.  
Now all placeholders should be replaced with the variable. Thanks for reporting.  

For the custom tags, you can follow the guide here about how to add new tags [CONTRIBUTING.md](https://github.com/maxnatchanon/vscode-go-struct-tag-autogen/blob/main/CONTRIBUTING.md).
