### ISSUE TITLE
Add more tags supporting

### ISSUE THREAD

**Issue by morilog** [maxnatchanon/vscode-go-struct-tag-autogen#7]
Please add a way to add new tags dynamically or, add `yaml`, `env` and, `env-default` tags support.
Thank you for your elegant extension.

**Comment by maxnatchanon** [comment]
Hi. I've release 1.1.0 with dynamic tag support. Here's the [config detail](https://github.com/maxnatchanon/vscode-go-struct-tag-autogen#tag-autocomplete-config).   
Please let me know if you find any issues.
